version: 5.1-{branch}+{build}

image: Visual Studio 2019

environment:
  MSYSTEM: MINGW64

for:
-
  branches:
    only:
      - master
  environment:
    matrix:
      - WITH_DEBUG_SYMBOLS: false
      - WITH_DEBUG_SYMBOLS: true
-
  environment:
    WITH_DEBUG_SYMBOLS: true

artifacts:
  - path: '*nightly.exe'

build_script:
  - C:\msys64\usr\bin\pacman -Syuu --noconfirm
  - C:\msys64\usr\bin\bash -lc "$(cygpath ${APPVEYOR_BUILD_FOLDER})/ci/build_windows.sh"

deploy:
  - provider: GitHub
    tag: nightly
    auth_token:
      secure: 9tKkhsqR9qSoKt3390923aZ0EauffZQQ/6Ho0HdYlTEudtFJ1eTnw6B3TGclgqA0 # your encrypted token from GitHub
    artifact: win.KNOSSOS.nightly.exe
    prerelease: true
    force_update: true
    on:
      branch: master
      WITH_DEBUG_SYMBOLS: false
  - provider: GitHub
    tag: nightly-dev
    auth_token:
      secure: 9tKkhsqR9qSoKt3390923aZ0EauffZQQ/6Ho0HdYlTEudtFJ1eTnw6B3TGclgqA0 # your encrypted token from GitHub
    artifact: /win\..*-KNOSSOS.nightly\.exe/
    prerelease: true
    force_update: true
    on:
      WITH_DEBUG_SYMBOLS: true