language: minimal

git:
  depth: false # tags for git describe may be farther away than the default depth

matrix:
  include:
    - os: linux
      dist: xenial
      services: docker
      env: TRAVIS_TAG=nightly
    - os: linux
      dist: xenial
      services: docker
      env: TRAVIS_TAG=nightly-dev
    - os: osx
      sudo: enabled
      env: TRAVIS_TAG=nightly
      addons:
        homebrew:
          packages:
            - boost
            - ninja
            - qt
            - quazip
            - snappy
          update: true
    - os: osx
      sudo: enabled
      env: TRAVIS_TAG=nightly-dev
      addons:
        homebrew:
          packages:
            - boost
            - ninja
            - qt
            - quazip
            - snappy
          update: true
  exclude:
    - if: branch != master
      env: TRAVIS_TAG=nightly

script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then docker pull knossostool/knossos; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then docker run -it --privileged --cap-add=ALL -v /lib/modules:/lib/modules -v /dev:/dev -v ${PWD}:/root/knossos -e TRAVIS_BRANCH -e TRAVIS_TAG knossostool/knossos bash -c '/root/knossos/ci/build_linux.sh'; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then sh $TRAVIS_BUILD_DIR/ci/build_macos.sh; fi

deploy:
  - provider: releases
    api_key:
      secure: "DHBayH59cTgSeuzw0umwjc52r5p1sR3EV1vOG77cK1NIb7fi2UVmx69V2mIzfGYp0t1uFDsVvDGtFYRQxKozCteBu2oinmbiSjbeWnyldQqTFnF4QONF+eWGiHNdOdHY7Tj37+eV5BlgfsXZ5MfLN3tXZ2y++D+yfoUItsbvC3I="
    file_glob: true
    file:
      - "linux.KNOSSOS.nightly.AppImage"
      - "macos.KNOSSOS.nightly.app.zip"
    skip_cleanup: true
    overwrite: true
    on:
      repo: knossos-project/knossos
      branch: master
      condition: $TRAVIS_TAG = nightly
  - provider: releases
    api_key:
      secure: "DHBayH59cTgSeuzw0umwjc52r5p1sR3EV1vOG77cK1NIb7fi2UVmx69V2mIzfGYp0t1uFDsVvDGtFYRQxKozCteBu2oinmbiSjbeWnyldQqTFnF4QONF+eWGiHNdOdHY7Tj37+eV5BlgfsXZ5MfLN3tXZ2y++D+yfoUItsbvC3I="
    file_glob: true
    file:
      - "linux.*-KNOSSOS.nightly.AppImage"
      - "macos.*-KNOSSOS.nightly.app.zip"
    skip_cleanup: true
    overwrite: true
    on:
      repo: knossos-project/knossos
      all_branches: true
      condition: $TRAVIS_TAG = nightly-dev
